### ISSUE TITLE
bump.lua crash

### ISSUE THREAD

**Issue by camchenry** [camchenry/super_shooter#14]
https://www.dropbox.com/s/1y4wa1exfps89j9/2016-03-11%2015_23_22-C__Users_Bobby_Documents_GitHub_super_shooter_entities_enemy_enemy.lua%20%28super_sh.png

**Comment by Nuthen** [comment]
Only happens when dying while outside the world

**Comment by Nuthen** [comment]
Fixed in commit 098fd79
